---
- name: demostrate keyword
  hosts: all
  gather_facts: True
  vars:
    supported_distros:
      - RedHat
      - Centos

  tasks:
    - name: install stuff
      yum:
        name: httpd
        state: present
      when: ansible_distribution == "RedHat"
