---
- name: Set up webservers
  hosts: threeandfour
  vars:
    firewall_pkg: ufw
    firewall_svc: ufw
    web_pkg: apache2
    web_svc: apache2
    ssl_pkg: mod_ssl
    httpdconf_src: files/httpd.conf
    httpdconf_dest: /etc/httpd/conf/httpd.conf
    htaccess_src: files/.htaccess
    secrets_dir: /etc/httpd/secrets
    secrets_src: files/htpasswd
    secrets_dest: "{{ secrets_dir }}/htpasswd"
    web_root: /var/www/html
  tasks:
    - name: install sw
      apt:
        state: latest
        pkg:
        - "{{ firewall_pkg }}"
        - "{{ web_pkg }}"


